#!/bin/bash
# meta: nostate

set -euo pipefail

echo "TODO: Fix cask upgrade"
exit 0

if [ ! -x "`which cask`" ]; then
    echo "Cask not found. Installing"
    curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
else
    cask upgrade-cask
fi
