#!/bin/bash

# Update to or install the newest version of duplicacy

set -euo pipefail

BIN=${UPDATE_BIN_TARGET}/duplicacy

cur_ver="$1"
new_ver="`git-most-recent-tag https://github.com/gilbertchen/duplicacy`"

new_bin="duplicacy_linux_x64_$new_ver"

if [ "$cur_ver" != "$new_ver" ]; then
    echo "New version available. Upgrading from $cur_ver to $new_ver" > /dev/null
    wget "https://github.com/gilbertchen/duplicacy/releases/download/v$new_ver/$new_bin" -O "$BIN"
    chmod +x "$BIN"
else
    echo "Most recent version $new_ver installed. Not updating" > /dev/null
fi

echo "$new_ver"
exit 0
