#!/usr/bin/env Rscript
# meta: nostate

update.packages(
    oldPkgs = as.data.frame(installed.packages(.libPaths()[1]))$Package,
    ask = FALSE, checkBuilt = TRUE, repos = "https://cloud.r-project.org/")
