#!/bin/bash
#
#
# Script for getting the most recent (according to sort
# --version-sort) tag from a remote git repository. Currently only
# matches tags consisting entirely of [0-9.] with an optional leading
# v. We'll see how far that takes us.


set -euo pipefail

if [ $# -lt 1 ]; then
    echo "usage: git-most-recent-tag <github url>"
    exit 1
fi

fail () {
    echo "No matching repository tags found"
    exit 1
}


url="$1"

git ls-remote "$url" |\
    grep tags |\
    awk '{print $2}' |\
    awk -F'/' '{print $3}' |\
    grep -E '^v?[0-9.]*$' |\
    tr -d 'v' |\
    sort --version-sort |\
    tail -1 || fail

exit 0
