#!/bin/bash

set -euo pipefail

# Script or cleaning up local branches deleted on the remote

git fetch --all -p -P

git branch -vv | grep 'gone]' | awk '{print $1}' | while read -r branch; do
    git branch -d "$branch" || true
done
