#!/bin/bash

if [ $# -ne 1 ] ; then
  echo "Usage: ssh-add-pass passfile [keyfile]"
  exit 1
fi

#eval $(ssh-agent)
pass=$(cat $1)

expect << EOF
  spawn ssh-add $2
  expect "Enter passphrase"
  send "$pass\r"
  expect eof
EOF

